///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String fontPoppinsBold = 'assets/font/Poppins-Bold.ttf';
  static const String fontPoppinsLight = 'assets/font/Poppins-Light.ttf';
  static const String fontPoppinsMedium = 'assets/font/Poppins-Medium.ttf';
  static const String fontPoppinsRegular = 'assets/font/Poppins-Regular.ttf';
  static const String fontPoppinsSemiBold = 'assets/font/Poppins-SemiBold.ttf';
  static const String fontPoppinsThin = 'assets/font/Poppins-Thin.ttf';
  static const String iconsFavicon = 'assets/icons/favicon.png';
  static const String iconsSign = 'assets/icons/sign.png';
  static const String imagesLogo = 'assets/images/logo.png';

}
