///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String fontPoppinsBold = 'assets/font/Poppins-Bold.ttf';
  static const String fontPoppinsLight = 'assets/font/Poppins-Light.ttf';
  static const String fontPoppinsMedium = 'assets/font/Poppins-Medium.ttf';
  static const String fontPoppinsRegular = 'assets/font/Poppins-Regular.ttf';
  static const String fontPoppinsSemiBold = 'assets/font/Poppins-SemiBold.ttf';
  static const String fontPoppinsThin = 'assets/font/Poppins-Thin.ttf';
  static const String iconsAddress = 'assets/icons/address.png';
  static const String iconsFavicon = 'assets/icons/favicon.png';
  static const String iconsFigma = 'assets/icons/figma.png';
  static const String iconsGit = 'assets/icons/git.png';
  static const String iconsGithub = 'assets/icons/github.png';
  static const String iconsIconCopy = 'assets/icons/icon-copy.png';
  static const String iconsIconEmail = 'assets/icons/icon-email.png';
  static const String iconsIconFigma = 'assets/icons/icon-figma.webp';
  static const String iconsIconFlutter = 'assets/icons/icon-flutter.png';
  static const String iconsIconPhone = 'assets/icons/icon-phone.png';
  static const String iconsSign = 'assets/icons/sign.png';
  static const String iconsTwitter = 'assets/icons/twitter.png';
  static const String imagesLogo = 'assets/images/logo.png';
  static const String imagesPersonal = 'assets/images/personal.JPG';
  static const String imagesPersonal1 = 'assets/images/personal1.JPG';
  static const String imagesSmartinnotechLogo = 'assets/images/smartinnotech_logo.png';
  static const String imagesWellcareLogo = 'assets/images/wellcare_logo.jpeg';

}
